name: TCMB Veri Tetikleyici

on:
  schedule:
    # Her Cuma TSİ 18:00'de otomatik çalışır
    - cron: '0 15 * * 5'
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Kütüphaneleri Yükle
        run: pip install requests curl_cffi
      - name: Kodu Çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
